apiVersion: v1
kind: PersistentVolume
metadata:
  name: gateway-state-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/alejandroacho/Server/.gateway-state
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-state-pvc
  namespace: blackwell
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: gateway-state-pv
